<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release;SelfContained</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
	  <DebugType>none</DebugType>
	  <DebugSymbols>false</DebugSymbols>
	  <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'SelfContained'">
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <PublishSingleFile>true</PublishSingleFile>
	  <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	  <SelfContained>true</SelfContained>
	  <_SuppressWpfTrimError>true</_SuppressWpfTrimError>
	  <PublishTrimmed>true</PublishTrimmed>
	  <TrimMode>partial</TrimMode>
	  <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GDUTClassHelper.Core\GDUTClassHelper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="View\Pages\CalendarPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
